allowBuilds:
  '@abandonware/noble': true
  '@serialport/bindings-cpp': true
  '@stoprocent/bluetooth-hci-socket': true
  '@stoprocent/noble': true
  electron: true
  electron-winstaller: true
  es5-ext: set this to true or false
  esbuild: true
  fs-xattr: true
  macos-alias: true
  usb: true
allowedDeprecatedVersions:
  "@npmcli/move-file": "2.0.1"
  are-we-there-yet: "2.0.0"
  boolean: "3.2.0"
  gar: "1.0.4"
  gauge: "3.0.2"
  glob: "7 || 8 || 10.5.0"
  inflight: "1.0.6"
  lodash.get: "4.4.2"
  npmlog: "5.0.1"
  rimraf: "2 || 3"
  tar: "6.2.1"
blockExoticSubdeps: false
nodeLinker: hoisted
overrides:
  '@andyshinn/meshcore-ts': link:../meshcore-ts
  "@types/parse-path": "npm:parse-path@7.1.0"
  extract-zip: npm:@electron-internal/extract-zip@1.0.3
